version: '3.8'

services:
  ollama:
    build:
      context: .
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    networks:
      ollama:
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              device_ids:
                - nvidia.com/gpu=all

  open-ui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "8000:8080"
    volumes:
      - open-webui:/app/backend/data
    restart: always
    environment:
      HF_HUB_OFFLINE: 1
      OLLAMA_BASE_URL: http://ollama:11434
    networks:
      ollama:
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              device_ids:
                - nvidia.com/gpu=all

volumes:
  ollama:
  open-webui:

networks:
  ollama:
